### ISSUE TITLE
[QUESTION]: Unable to use use HTB-Toolkit & its VPN

### ISSUE THREAD

**Issue by 0xDangerChonk** [Athena-OS/athena#140]
## Question

Hello - I've just set my API key onto the htb-toolkit so I can prepare to spin up the machines and complete them within the environment. However, when I did `htb-toolkit -k {VPN_HERE}` - this error message came up:

```
thread 'tokio-runtime-worker' panicked at src/vpn.rs:277:85:
called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at src/vpn.rs:340:25:
Blocking task failed: JoinError::Panic(Id(3), ...)
```

This happens for both UDP & TCP Connections to the VPN.

**Comment by D3vil0p3r** [comment]
Hello! That error is due to invalid HTB App Token. Are you sure your App Token is still valid? (ps: the argument is `-v` instead of `-k`)

**Comment by Beegchonk** [comment]
Yes, I even regenerates my token but I can try again

**Comment by D3vil0p3r** [comment]
Ok @Beegchonk let me know.

**Comment by Beegchonk** [comment]
> Ok @Beegchonk let me know.

Hello D3vil0p3r - I am sorry for the delayed response but I've tried again today and I've gotten the same result - even after manually typing out my entire API token.

**Comment by D3vil0p3r** [comment]
Which VPN are you trying to connect to? Are you a Free or VIP or VIP+ user?

**Comment by D3vil0p3r** [comment]
Any news or the issue can be closed?

**Comment by IAmNewbieZ** [comment]
@D3vil0p3r I use htb-toolkit normally. But I have another problem that Pwnage Menu doesn't show any machines or staring point machines

![Image](https://github.com/user-attachments/assets/f7789dc6-9b75-4227-94f5-33f3d65da72f)

**Comment by D3vil0p3r** [comment]
Which message you get when you run `htb-toolkit -l free`?

**Comment by IAmNewbieZ** [comment]
> Which message you get when you run `htb-toolkit -l free`?

Yeah it shows every free machines. But when I use the Pwnage Menu, it doesn't show like the `htb-tookit` does

**Comment by IAmNewbieZ** [comment]
Here is my output of `htb-toolkit -l free`

![Image](https://github.com/user-attachments/assets/b7ee2ce3-79f8-4aba-ba2d-3120b11f0941)

**Comment by D3vil0p3r** [comment]
Ah yes.... Omg it works on FlyPie menu but now I replaced it by Kando and I didn't adapted htb-toolkit to it. I'm currently working on Fedora feasibility study on Athena, but you can use htb-toolkit command line to run free and retired machines. Note that starting point machines don't work because HTB dropped the APIs the tool used to run them.

**Comment by IAmNewbieZ** [comment]
OK I see. Thank you for your support.
